[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
console_output_style = "count"
testpaths = ["src",
             "test/",
             ]
