name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: "Test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [
          "Ubuntu 18.04 - Python 3.6",
          "Ubuntu 20.04 - Python 3.8"
        ]

        include:
          - name: "Ubuntu 18.04 - Python 3.6"
            os: "ubuntu-18.04"
            python: "3.6"
          - name: "Ubuntu 20.04 - Python 3.8"
            os: "ubuntu-20.04"
            python: "3.8"

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2

      - name: "Set up Python ${{ matrix.python }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: "Install dependencies"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8
          python3 -m pip install -r test/requirements.txt

      - name: "Style check"
        run: |
          make style

      - name: "Execute tests"
        run: |
          make test
